# Generated by Django 3.2.5 on 2021-08-06 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('semester', models.CharField(max_length=255, verbose_name='semester')),
                ('series_num', models.CharField(max_length=255, verbose_name='series_num')),
                ('num', models.CharField(blank=True, max_length=255, verbose_name='num')),
                ('category', models.CharField(blank=True, max_length=255, verbose_name='category')),
                ('department', models.CharField(max_length=255, verbose_name='department')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('professor', models.CharField(blank=True, max_length=255, verbose_name='professor')),
                ('credit', models.CharField(blank=True, max_length=255, verbose_name='credit')),
                ('namecomma', models.CharField(max_length=255, verbose_name='namecomma')),
                ('namespaced', models.CharField(max_length=255, verbose_name='namespaced')),
                ('words', models.TextField(blank=True, verbose_name='words')),
                ('keywords_3', models.TextField(blank=True, verbose_name='keywords_3')),
                ('keywords_5', models.TextField(blank=True, verbose_name='keywords_5')),
                ('keywords_20', models.TextField(blank=True, verbose_name='keywords_20')),
            ],
            options={
                'ordering': ('subid',),
            },
        ),
        migrations.CreateModel(
            name='Kmooc',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('midclassify', models.CharField(max_length=255, verbose_name='midclassify')),
                ('level', models.CharField(max_length=255, verbose_name='level')),
                ('image', models.URLField(verbose_name='image')),
                ('link', models.URLField(verbose_name='link')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_mooc', to='cafeapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeapp.blog')),
            ],
        ),
    ]
